# GLOBAL SITE SETTINGS

# General
seo_title: "Westlaw"
title: "Westlaw Prototype"
company: "Thomson Reuters"
description: ""

# Contact Info
email: support@thomsonreuters.com
phone: 1800 020 548
fax: (05) 555 555

# Social Networks
facebook: ""

# Top Menu
top_menu:
  - title: Home
    url: /pages/westlaw/
    icon: fi-home
    visibility:

  - title: Research
    url: /pages/westlaw/research/search-templates/basic/
    icon: fi-magnifying-glass
    visibility:

  - title: Workflow
    url: /pages/westlaw/workflow/
    icon: fi-graph-bar
    visibility:

  - title: Tools
    url: /pages/westlaw/tools/
    icon: fi-wrench
    visibility:

  - title: Newsroom
    url: /pages/westlaw/newsroom/
    icon: fi-info
    visibility:

  - title: Guide
    url: /pages/westlaw/guide/
    icon: fi-book
    visibility:
    exclude_from_guide: true

# User Menu
user_menu:
  - title: Alerts
    url: /pages/westlaw/alerts/
    icon: fi-megaphone
    visibility:

  - title: Folders
    url: /pages/westlaw/folders/
    icon: fi-folder
    visibility:

  - title: Contacts
    url: "/modal_output/westlaw/coming-soon.html"
    icon: fi-address-book
    visibility:
    modal: ajax-modal
    exclude_from_guide: true

  - title: History
    url: "#coming"
    icon: fi-clock
    visibility:

  - title: Client ID
    url: "/modal_output/westlaw/change-client-id.html"
    icon: fi-torso
    visibility:
    modal: ajax-modal
    exclude_from_guide: true

  - title: Preferences
    url: /pages/westlaw/user/preferences/
    icon: fi-widget
    visibility:

  - title: Help
    url: "http://training.thomsonreuters.com.au/products/westlaw-au/"
    icon: fi-info
    visibility: hide-for-large-up
    exclude_from_guide: true

# Touch Menu
touch_menu:
  - title: Home
    url: /pages/westlaw/
    id: home-btn
    icon: fi-home
    visibility:

  - title: Hints
    url: "#"
    id: hints-btn
    icon: fi-lightbulb
    visibility:

  - title: Links
    url: "#"
    id: favourites-btn
    icon: fi-star
    visibility:

  - title: History
    url: "#"
    id: history-btn
    icon: fi-clock
    visibility:

# Links
thomson_reuters_au: "http://www.thomsonreuters.com.au"
help: "http://training.thomsonreuters.com.au/products/westlaw-au/"
privacy_policy: "http://www.thomsonreuters.com.au/terms/privacy-policy.aspx"
terms_of_use: "http://www.thomsonreuters.com.au/terms/online-terms-of-use.aspx"
feedback: "http://www.nicereply.com/thomson-reuters-anz.wlau/westlaw-au"

# International Sites
sites:
  - title: Westlaw Next
    url: "http://a.next.westlaw.com"
    icon: fi-web
  - title: Westlaw International
    url: "http://www.westlaw.co.nz"
    icon: fi-web
  - title: Westlaw UK
    url: "http://login.wesklaw.co.uk"
    icon: flag-icon-gb
  - title: Westlaw CN
    url: "http://app.westlawchina.com"
    icon: flag-icon-cn
  - title: Westlaw HK
    url: "http://login.westlaw.com.hk"
    icon: flag-icon-hk
  - title: Checkpoint AU
    url: "http://checkpointau.com.au"
    icon: flag-icon-au
  - title: Checkpoint World
    url: "https://www.checkpointworld.com"
    icon: fi-web
  - title: Proview
    url: "http://thomsonreuters.com/site/proview/"
    icon: fi-web