# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: prototypes

# Grunt handles images and assets.
exclude: ['img', 'css', 'scripts', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
permalink: pretty

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

kramdown:
  input: GFM

# pygments: true - deprecated?
highlighter: pygments

# https://github.com/jekyll/jekyll-sitemap
# If you would like to exclude specific pages/posts from the sitemap set the sitemap flag to false in the front matter for the page/post.
#
# sitemap: false

gems:
  - jekyll-sitemap

#----------------------------------------------------------------
# Collections
# ---------------------------------------------------------------

collections:
  docs:
    output: true
    permalink: /docs/:path/

#----------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
      type: "docs" # a collection in your site, in plural form
    values:
      layout: "common/public/docs"
      site_type: "westlaw" # one or the other, doesn't matter
      context_menu: "common/docs/context_menu_content.html"
  -
    scope:
      path: "pages/westlaw"
    values:
      site_type: "westlaw"
  -
    scope:
      path: "pages/checkpoint"
    values:
      site_type: "checkpoint"

